config/routes.rb
PhotoWander::Application.routes.draw do
  root 'go_stamp_rally#index' #トップページ
  get 'detail/' => 'go_stamp_rally#detail' #rallyの一覧を表示
  get 'api/rally-lists' => 'go_stamp_rally#rally_lists' #rallyListのjsonを返す
  get 'rallies/' => 'rallies#index'

  get 'login/'  => 'login#login_form' #ログインフォーム画面
  post 'login/' => 'login#login_auth' #ログイン認証
  get 'logout/' => 'login#logout' #ログアウト

  resources :stamps

  resources :checkpoints

  resources :entry_cards

  resources :rallies

  resources :users

end

app/models/checkpoint.rb
class Checkpoint < ActiveRecord::Base
  belongs_to :rally
  has_many :stamps 
end

app/controllers/checkpoints_controller.rb
class CheckpointsController < ApplicationController
  before_action :set_checkpoint, only: [:show, :edit, :update, :destroy]

  # GET /checkpoints
  # GET /checkpoints.json
  def index
    @checkpoints = Checkpoint.all
  end

  # GET /checkpoints/1
  # GET /checkpoints/1.json
  def show
  end

  # GET /checkpoints/new
  def new
    @checkpoint = Checkpoint.new
  end

  # GET /checkpoints/1/edit
  def edit
  end

  # POST /checkpoints
  # POST /checkpoints.json
  def create
    @checkpoint = Checkpoint.new(checkpoint_params)

    respond_to do |format|
      if @checkpoint.save
        format.html { redirect_to @checkpoint, notice: 'Checkpoint was successfully created.' }
        format.json { render action: 'show', status: :created, location: @checkpoint }
      else
        format.html { render action: 'new' }
        format.json { render json: @checkpoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /checkpoints/1
  # PATCH/PUT /checkpoints/1.json
  def update
    respond_to do |format|
      if @checkpoint.update(checkpoint_params)
        format.html { redirect_to @checkpoint, notice: 'Checkpoint was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @checkpoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checkpoints/1
  # DELETE /checkpoints/1.json
  def destroy
    @checkpoint.destroy
    respond_to do |format|
      format.html { redirect_to checkpoints_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_checkpoint
      @checkpoint = Checkpoint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def checkpoint_params
      params.require(:checkpoint).permit(:ucode, :name, :lat, :lng, :radius)
    end
end

app/helpers/checkpoints_helper.rb
module CheckpointsHelper
end

app/views/checkpoints/_form.html.erb
<%= form_for(@checkpoint) do |f| %>
  <% if @checkpoint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@checkpoint.errors.count, "error") %> prohibited this checkpoint from being saved:</h2>

      <ul>
      <% @checkpoint.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ucode %><br>
    <%= f.text_field :ucode %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br>
    <%= f.text_field :lng %>
  </div>
  <div class="field">
    <%= f.label :radius %><br>
    <%= f.number_field :radius %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/checkpoints/edit.html.erb
<h1>Editing checkpoint</h1>

<%= render 'form' %>

<%= link_to 'Show', @checkpoint %> |
<%= link_to 'Back', checkpoints_path %>

app/views/checkpoints/index.html.erb
<h1>Listing checkpoints</h1>

<table>
  <thead>
    <tr>
      <th>Ucode</th>
      <th>Name</th>
      <th>Lat</th>
      <th>Lng</th>
      <th>Radius</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @checkpoints.each do |checkpoint| %>
      <tr>
        <td><%= checkpoint.ucode %></td>
        <td><%= checkpoint.name %></td>
        <td><%= checkpoint.lat %></td>
        <td><%= checkpoint.lng %></td>
        <td><%= checkpoint.radius %></td>
        <td><%= link_to 'Show', checkpoint %></td>
        <td><%= link_to 'Edit', edit_checkpoint_path(checkpoint) %></td>
        <td><%= link_to 'Destroy', checkpoint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Checkpoint', new_checkpoint_path %>

app/views/checkpoints/new.html.erb
<h1>New checkpoint</h1>

<%= render 'form' %>

<%= link_to 'Back', checkpoints_path %>

app/views/checkpoints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ucode:</strong>
  <%= @checkpoint.ucode %>
</p>

<p>
  <strong>Name:</strong>
  <%= @checkpoint.name %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @checkpoint.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @checkpoint.lng %>
</p>

<p>
  <strong>Radius:</strong>
  <%= @checkpoint.radius %>
</p>

<%= link_to 'Edit', edit_checkpoint_path(@checkpoint) %> |
<%= link_to 'Back', checkpoints_path %>