config/routes.rb
PhotoWander::Application.routes.draw do
  root 'go_stamp_rally#index' #トップページ
  get 'detail/' => 'go_stamp_rally#detail' #rallyの一覧を表示
  get 'api/rally-lists' => 'go_stamp_rally#rally_lists' #rallyListのjsonを返す
  get 'rallies/' => 'rallies#index'

  get 'login/'  => 'login#login_form' #ログインフォーム画面
  post 'login/' => 'login#login_auth' #ログイン認証
  get 'logout/' => 'login#logout' #ログアウト

  resources :stamps

  resources :checkpoints

  resources :entry_cards

  resources :rallies

  resources :users

end

app/models/entry_card.rb
class EntryCard < ActiveRecord::Base
  belongs_to :rally
  has_many :stamps 
  
  def checkpoints
    # スタンプ済みのデータを格納する。
    my_stamps = []
    stamps.each do |stamp|
      my_stamps << stamp
    end
    # checkpointの格納先
    _checkpoints = []
    rally.checkpoints.each do |checkpoint|
      class << checkpoint
        # checkpointの特異メソッド
        attr_accessor :stamp
      end
      
      # checkpointに自分のスタンプが押されているか否か
      unless my_stamp = my_stamps.select{|item| item.checkpoint_id == checkpoint.id}.blank?
        checkpoint.stamp = my_stamp
      else
        checkpoint.stamp = my_stamp
      end
      
      _checkpoints << checkpoint
    end
    
    _checkpoints
  end
end

app/controllers/entry_cards_controller.rb
class EntryCardsController < ApplicationController
  before_action :set_entry_card, only: [:show, :edit, :update, :destroy]
  
  def entry_list
    @user = User.find(current_user.id)
    @entry_cards = @user.entry_cards
  end
  
  # GET /entry_cards
  # GET /entry_cards.json
  def index
    @entry_cards = EntryCard.all
  end

  # GET /entry_cards/1
  # GET /entry_cards/1.json
  def show
  end

  # GET /entry_cards/new
  def new
    @entry_card = EntryCard.new
  end

  # GET /entry_cards/1/edit
  def edit
  end

  # POST /entry_cards
  # POST /entry_cards.json
  def create
    @entry_card = EntryCard.new(entry_card_params)

    respond_to do |format|
      if @entry_card.save
        format.html { redirect_to @entry_card, notice: 'Entry card was successfully created.' }
        format.json { render action: 'show', status: :created, location: @entry_card }
      else
        format.html { render action: 'new' }
        format.json { render json: @entry_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entry_cards/1
  # PATCH/PUT /entry_cards/1.json
  def update
    respond_to do |format|
      if @entry_card.update(entry_card_params)
        format.html { redirect_to @entry_card, notice: 'Entry card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @entry_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entry_cards/1
  # DELETE /entry_cards/1.json
  def destroy
    @entry_card.destroy
    respond_to do |format|
      format.html { redirect_to entry_cards_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry_card
      @entry_card = EntryCard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_card_params
      params.require(:entry_card).permit(:finish_flag, :user_id, :rally_id)
    end
end

app/helpers/entry_cards_helper.rb
module EntryCardsHelper
end

app/views/entry_cards/_form.html.erb
<%= form_for(@entry_card) do |f| %>
  <% if @entry_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry_card.errors.count, "error") %> prohibited this entry_card from being saved:</h2>

      <ul>
      <% @entry_card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :finish_flag %><br>
    <%= f.check_box :finish_flag %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :rally_id %><br>
    <%= f.number_field :rally_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entry_cards/edit.html.erb
<h1>Editing entry_card</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry_card %> |
<%= link_to 'Back', entry_cards_path %>

app/views/entry_cards/entry_list.html.erb
<%= render 'layouts/header' %>
<div data-role="collapsibleset" data-theme="a" data-content-theme="a">
<% @entry_cards.each do |entry_card| %>
  <div data-role="collapsible">
    <h3><%= entry_card.rally.title %><h3>
    <p><%= entry_card.rally.detail %></p>
    <p><%= entry_card.rally.opening %></p>
    <p><%= entry_card.rally.ending %></p>
    <%= link_to 'プレイ', controller: 'play', action: 'index', rally_id: entry_card.rally.id %>
  </div>
<% end %>
<%= render 'layouts/footer' %>

app/views/entry_cards/index.html.erb
<h1>Listing entry_cards</h1>

<table>
  <thead>
    <tr>
      <th>Finish flag</th>
      <th>User</th>
      <th>Rally</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @entry_cards.each do |entry_card| %>
      <tr>
        <td><%= entry_card.finish_flag %></td>
        <td><%= entry_card.user_id %></td>
        <td><%= entry_card.rally_id %></td>
        <td><%= link_to 'Show', entry_card %></td>
        <td><%= link_to 'Edit', edit_entry_card_path(entry_card) %></td>
        <td><%= link_to 'Destroy', entry_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry card', new_entry_card_path %>

app/views/entry_cards/new.html.erb
<h1>New entry_card</h1>

<%= render 'form' %>

<%= link_to 'Back', entry_cards_path %>

app/views/entry_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Finish flag:</strong>
  <%= @entry_card.finish_flag %>
</p>

<p>
  <strong>User:</strong>
  <%= @entry_card.user_id %>
</p>

<p>
  <strong>Rally:</strong>
  <%= @entry_card.rally_id %>
</p>

<%= link_to 'Edit', edit_entry_card_path(@entry_card) %> |
<%= link_to 'Back', entry_cards_path %>