config/routes.rb
PhotoWander::Application.routes.draw do
  root 'go_stamp_rally#index' #トップページ
  get 'detail/' => 'go_stamp_rally#detail' #rallyの一覧を表示
  get 'api/rally-lists' => 'go_stamp_rally#rally_lists' #rallyListのjsonを返す
  get 'rallies/' => 'rallies#index'

  get 'login/'  => 'login#login_form' #ログインフォーム画面
  post 'login/' => 'login#login_auth' #ログイン認証
  get 'logout/' => 'login#logout' #ログアウト

  resources :stamps

  resources :checkpoints

  resources :entry_cards

  resources :rallies

  resources :users

end

app/models/stamp.rb
class Stamp < ActiveRecord::Base
  belongs_to :checkpoint
  belongs_to :entry_card
  
  attr_accessor :pic
  before_create :store_file
  before_destroy :destroy_file
  
  private
    def store_file
      #ファイル名の取得
      self.file_name = Time.now.to_i.to_s + '_' + Digest::MD5.hexdigest(self.pic.original_filename) + '.jpg'
      File.open(full_path, 'wb') do |f|
        f.write self.pic.read
      end
    end
    
    def destroy_file
      begin
        File.unlink full_path
      rescue
        nil
      end
    end
    
    def full_path
      return Rails.root.join('public/pictures/').to_s + self.file_name
    end
end

app/controllers/stamps_controller.rb
class StampsController < ApplicationController
  before_action :set_stamp, only: [:show, :edit, :update, :destroy]

  # GET /stamps
  # GET /stamps.json
  def index
    @stamps = Stamp.all
  end

  # GET /stamps/1
  # GET /stamps/1.json
  def show
  end

  # GET /stamps/new
  def new
    @stamp = Stamp.new
  end

  # GET /stamps/1/edit
  def edit
  end

  # POST /stamps
  # POST /stamps.json
  def create
    @stamp = Stamp.new(stamp_params)

    respond_to do |format|
      if @stamp.save
        format.html { redirect_to @stamp, notice: 'Stamp was successfully created.' }
        format.json { render action: 'show', status: :created, location: @stamp }
      else
        format.html { render action: 'new' }
        format.json { render json: @stamp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stamps/1
  # PATCH/PUT /stamps/1.json
  def update
    respond_to do |format|
      if @stamp.update(stamp_params)
        format.html { redirect_to @stamp, notice: 'Stamp was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @stamp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stamps/1
  # DELETE /stamps/1.json
  def destroy
    @stamp.destroy
    respond_to do |format|
      format.html { redirect_to stamps_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stamp
      @stamp = Stamp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stamp_params
      params.require(:stamp).permit(:file_name, :file_type, :file_size, :file_width, :file_height, :checkpoint_id, :entry_card_id, :pic)
    end
end

app/helpers/stamps_helper.rb
module StampsHelper
end

app/views/stamps/_form.html.erb
<%= form_for(@stamp) do |f| %>
  <% if @stamp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stamp.errors.count, "error") %> prohibited this stamp from being saved:</h2>

      <ul>
      <% @stamp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file_name %><br>
    <%= f.file_field :pic %>
  </div>
  <div class="field">
    <%= f.label :file_type %><br>
    <%= f.text_field :file_type %>
  </div>
  <div class="field">
    <%= f.label :file_size %><br>
    <%= f.number_field :file_size %>
  </div>
  <div class="field">
    <%= f.label :file_width %><br>
    <%= f.number_field :file_width %>
  </div>
  <div class="field">
    <%= f.label :file_height %><br>
    <%= f.number_field :file_height %>
  </div>
  <div class="field">
    <%= f.label :checkpoint_id %><br>
    <%= f.number_field :checkpoint_id %>
  </div>
  <div class="field">
    <%= f.label :entry_card_id %><br>
    <%= f.number_field :entry_card_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stamps/edit.html.erb
<h1>Editing stamp</h1>

<%= render 'form' %>

<%= link_to 'Show', @stamp %> |
<%= link_to 'Back', stamps_path %>

app/views/stamps/index.html.erb
<h1>Listing stamps</h1>

<table>
  <thead>
    <tr>
      <th>File name</th>
      <th>File type</th>
      <th>File size</th>
      <th>File width</th>
      <th>File height</th>
      <th>Checkpoint</th>
      <th>Entry card</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stamps.each do |stamp| %>
      <tr>
        <td><%= stamp.file_name %></td>
        <td><%= stamp.file_type %></td>
        <td><%= stamp.file_size %></td>
        <td><%= stamp.file_width %></td>
        <td><%= stamp.file_height %></td>
        <td><%= stamp.checkpoint_id %></td>
        <td><%= stamp.entry_card_id %></td>
        <td><%= link_to 'Show', stamp %></td>
        <td><%= link_to 'Edit', edit_stamp_path(stamp) %></td>
        <td><%= link_to 'Destroy', stamp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stamp', new_stamp_path %>

app/views/stamps/new.html.erb
<h1>New stamp</h1>

<%= render 'form' %>

<%= link_to 'Back', stamps_path %>

app/views/stamps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>File name:</strong>
  <%= @stamp.file_name %>
</p>

<p>
  <strong>File type:</strong>
  <%= @stamp.file_type %>
</p>

<p>
  <strong>File size:</strong>
  <%= @stamp.file_size %>
</p>

<p>
  <strong>File width:</strong>
  <%= @stamp.file_width %>
</p>

<p>
  <strong>File height:</strong>
  <%= @stamp.file_height %>
</p>

<p>
  <strong>Checkpoint:</strong>
  <%= @stamp.checkpoint_id %>
</p>

<p>
  <strong>Entry card:</strong>
  <%= @stamp.entry_card_id %>
</p>

<%= link_to 'Edit', edit_stamp_path(@stamp) %> |
<%= link_to 'Back', stamps_path %>