config/routes.rb
PhotoWander::Application.routes.draw do
  root 'go_stamp_rally#index' #トップページ
  get 'detail/' => 'go_stamp_rally#detail' #rallyの一覧を表示
  get 'api/rally-lists' => 'go_stamp_rally#rally_lists' #rallyListのjsonを返す
  get 'rallies/' => 'rallies#index'

  get 'login/'  => 'login#login_form' #ログインフォーム画面
  post 'login/' => 'login#login_auth' #ログイン認証
  get 'logout/' => 'login#logout' #ログアウト

  resources :stamps

  resources :checkpoints

  resources :entry_cards

  resources :rallies

  resources :users

end

app/models/rally.rb
class Rally < ActiveRecord::Base
  has_many :checkpoints
  has_many :entry_cards
end

app/controllers/rallies_controller.rb
class RalliesController < ApplicationController
  before_action :set_rally, only: [:show, :edit, :update, :destroy]

  # GET /rallies
  # GET /rallies.json
  def index
    if current_user
      @user = User.find(current_user.id)
    end
    @rallies = Rally.all
  end

  # GET /rallies/1
  # GET /rallies/1.json
  def show
  end

  # GET /rallies/new
  def new
    @rally = Rally.new
  end

  # GET /rallies/1/edit
  def edit
  end

  # POST /rallies
  # POST /rallies.json
  def create
    @rally = Rally.new(rally_params)

    respond_to do |format|
      if @rally.save
        format.html { redirect_to @rally, notice: 'Rally was successfully created.' }
        format.json { render action: 'show', status: :created, location: @rally }
      else
        format.html { render action: 'new' }
        format.json { render json: @rally.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rallies/1
  # PATCH/PUT /rallies/1.json
  def update
    respond_to do |format|
      if @rally.update(rally_params)
        format.html { redirect_to @rally, notice: 'Rally was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @rally.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rallies/1
  # DELETE /rallies/1.json
  def destroy
    @rally.destroy
    respond_to do |format|
      format.html { redirect_to rallies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rally
      @rally = Rally.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rally_params
      params.require(:rally).permit(:title, :detail, :opening, :ending)
    end
end

app/helpers/rallies_helper.rb
module RalliesHelper
end

app/views/rallies/_form.html.erb
<%= form_for(@rally) do |f| %>
  <% if @rally.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rally.errors.count, "error") %> prohibited this rally from being saved:</h2>

      <ul>
      <% @rally.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :detail %><br>
    <%= f.text_area :detail %>
  </div>
  <div class="field">
    <%= f.label :opening %><br>
    <%= f.datetime_select :opening %>
  </div>
  <div class="field">
    <%= f.label :ending %><br>
    <%= f.datetime_select :ending %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rallies/edit.html.erb
<h1>Editing rally</h1>

<%= render 'form' %>

<%= link_to 'Show', @rally %> |
<%= link_to 'Back', rallies_path %>

app/views/rallies/index.html.erb
<h1>Listing rallies</h1>
<% if current_user %>
<%= @user.entry_cards.size %>個のラリーに参加中！
<% end %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Detail</th>
      <th>Opening</th>
      <th>Ending</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @rallies.each do |rally| %>
      <tr>
        <td><%= rally.detail %></td>
        <td><%= rally.opening %></td>
        <td><%= rally.ending %></td>
        <td><%= link_to 'Show', rally %></td>
        <td><%= link_to 'Edit', edit_rally_path(rally) %></td>
        <td><%= link_to 'Destroy', rally, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rally', new_rally_path %>

app/views/rallies/new.html.erb
<h1>New rally</h1>

<%= render 'form' %>

<%= link_to 'Back', rallies_path %>

app/views/rallies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @rally.title %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @rally.detail %>
</p>

<p>
  <strong>Opening:</strong>
  <%= @rally.opening %>
</p>

<p>
  <strong>Ending:</strong>
  <%= @rally.ending %>
</p>

<%= link_to 'Edit', edit_rally_path(@rally) %> |
<%= link_to 'Back', rallies_path %>